#include "system_interrupts.h"
#include "cmsis_os.h"
#include "app_header.h"

extern void __main(void);

// This hacky struct is generated by forcing the shim interrupt vectors into certain sections, 
// which have been named to guarantee that they will be placed at certain offsets in the flash image.
// These memory addresses CANNOT BE CHANGED unless the memory map is changed as well.

// IAR Embedded Workbench doesn't require this many hacks to get a ROPI vector table going. It will, 
// be default, generate address-relative function pointers when asked. 

// This struct is called __Vectors because Keil puts a "--first=__Vectors" command line arg into the linker command string
// and doesn't provide a way to change that.
const APP_HEADER HEADER __attribute__((section("__Header"))) __attribute__((used)) = {
	0,          // Space reserved in the image for a CRC32 checksum
	0xDEADBEEF, // the CRC32 start mark
	APP_VERSION, // test version
	(uint32_t)__main
};
